# Generated by Django 5.2.6 on 2025-09-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('section1', 'Section 1'), ('section2', 'Section 2'), ('section3', 'Section 3')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('overlay_title', models.CharField(blank=True, max_length=100, null=True)),
                ('overlay_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('bike_image', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('whatsapp_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('youtube_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('instagram_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('facebook_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('map_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('internet_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('phone_icon', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('address_line1', models.CharField(default='51, Rajaji Street', max_length=200)),
                ('address_line2', models.CharField(default='GST Road', max_length=200)),
                ('address_line3', models.CharField(default='Chengalpattu-603104', max_length=200)),
                ('website', models.URLField(default='https://www.DriveRp.in')),
                ('phone', models.CharField(default='+91 987 952 1234', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection3Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('section3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.aboutsection')),
            ],
        ),
    ]
