# Generated by Django 5.2.6 on 2025-09-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_brand_kmdriven_owner_sellbikesecondsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelname',
            name='brand',
        ),
        migrations.DeleteModel(
            name='KMDriven',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='model',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='SellBikeSecondSection',
        ),
        migrations.DeleteModel(
            name='SellBikeStep',
        ),
        migrations.DeleteModel(
            name='SellBikeTopBanner',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ModelName',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
