# Generated by Django 5.2.6 on 2025-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_sellbikepage_howitworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbikepage',
            name='second_banner_top_text',
            field=models.TextField(blank=True, help_text='Supports HTML tags', null=True),
        ),
    ]
