# Generated by Django 5.2.6 on 2025-09-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_alter_sellbikepage_second_banner_top_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Log in', max_length=100)),
                ('image', models.ImageField(upload_to='login_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
