# Generated by Django 5.2.6 on 2025-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_loginpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason', models.CharField(choices=[('support', 'Customer Support'), ('sales', 'Sales Inquiry'), ('feedback', 'Feedback'), ('partnership', 'Partnership'), ('careers', 'Careers'), ('other', 'Other')], max_length=50)),
                ('find_us', models.CharField(choices=[('google', 'Google'), ('social', 'Social Media'), ('friend', 'Friend / Referral'), ('ads', 'Advertisements'), ('events', 'Events'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
