# Generated by Django 5.2.6 on 2025-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='find_us',
            field=models.CharField(choices=[('google', 'Google'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Website', 'Website'), ('Facebook', 'Facebook'), ('OLX', 'OLX'), ('Walk-in', 'Walk-in')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('General Enquiry', 'General Enquiry'), ('Buy a Bike', 'Buy a Bike'), ('Sell a Bike', 'Sell a Bike'), ('Exchange a Bike', 'Exchange a Bike'), ('RTO Service', 'RTO Service'), ('other', 'Other')], max_length=50),
        ),
    ]
