# Generated by Django 5.2.6 on 2025-09-12 13:09

import bikes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_alter_contact_find_us_alter_contact_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('bike_model', models.CharField(blank=True, max_length=150)),
                ('bike_variant', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_cc', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('owners', models.CharField(blank=True, choices=[('1st Owner', '1st Owner'), ('2nd Owner', '2nd Owner'), ('3rd Owner', '3rd Owner'), ('4th+ Owner', '4th+ Owner')], max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto'), ('semi-auto', 'Semi-Auto')], max_length=12, null=True)),
                ('rto_state', models.CharField(blank=True, max_length=120)),
                ('rto_city', models.CharField(blank=True, max_length=120)),
                ('refurbished', models.BooleanField(default=False)),
                ('registration_certificate', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('warranty', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='buybikes/images/')),
                ('card_bg_image', models.ImageField(blank=True, null=True, upload_to='buybikes/card_bg/')),
                ('variant_image1', models.ImageField(blank=True, null=True, upload_to='buybikes/variants/')),
                ('variant_image2', models.ImageField(blank=True, null=True, upload_to='buybikes/variants/')),
                ('variant_image3', models.ImageField(blank=True, null=True, upload_to='buybikes/variants/')),
                ('variant_image4', models.ImageField(blank=True, null=True, upload_to='buybikes/variants/')),
                ('variant_image5', models.ImageField(blank=True, null=True, upload_to='buybikes/variants/')),
                ('ignition_type', models.CharField(blank=True, help_text='e.g. Kick & Self Start', max_length=120)),
                ('front_brake_type', models.CharField(blank=True, help_text='e.g. Drum / Disc', max_length=120)),
                ('rear_brake_type', models.CharField(blank=True, help_text='e.g. Drum / Disc', max_length=120)),
                ('abs', models.BooleanField(default=False)),
                ('odometer', models.CharField(blank=True, choices=[('analogue', 'Analogue'), ('digital', 'Digital'), ('both', 'Both')], max_length=20, null=True)),
                ('wheel_type', models.CharField(blank=True, help_text='e.g. Steel / Alloy', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buybike',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Buy Now', max_length=50)),
                ('trapezoid_image', models.ImageField(upload_to='hero/trapezoid/')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Big heading text', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=bikes.models.banner_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('bike_image', models.ImageField(upload_to='info_section/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LastSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Last Section',
                'verbose_name_plural': 'Last Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
            ],
        ),
        migrations.CreateModel(
            name='SupportFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='support_features/')),
                ('arrow_image', models.ImageField(blank=True, null=True, upload_to='support_features/arrows/')),
                ('arrow', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=bikes.models.testimonial_image_upload_to)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Real Stories From our Happy Customer', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='Their words drive us forward and inspire others to join the movement.', max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrustedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trusted by Riders Like You', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=bikes.models.trusted_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('test_drive_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('buybike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bikes.buybike')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/bike/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_images', to='bikes.herosection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LastSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the step image', upload_to='last_section/')),
                ('title', models.CharField(blank=True, help_text='Image title / caption', max_length=255, null=True)),
                ('order_no', models.PositiveSmallIntegerField(default=0, help_text='Order (0 = first)')),
                ('alt_text', models.CharField(blank=True, help_text='Optional alt text for accessibility', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.lastsection')),
            ],
            options={
                'verbose_name': 'Last Section Image',
                'verbose_name_plural': 'Last Section Images',
                'ordering': ['order_no', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='buybike',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buybikes', to='bikes.location'),
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=bikes.models.stat_icon_upload_to)),
                ('value', models.CharField(max_length=64)),
                ('caption', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bikes.homepagebanner')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
